// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dbmodel

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type categoriesTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *categoriesTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("news_categories").
func (v *categoriesTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *categoriesTableType) Columns() []string {
	return []string{
		"id",
		"news_id",
		"category_id",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *categoriesTableType) NewStruct() reform.Struct {
	return new(Categories)
}

// NewRecord makes a new record for that table.
func (v *categoriesTableType) NewRecord() reform.Record {
	return new(Categories)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *categoriesTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// CategoriesTable represents news_categories view or table in SQL database.
var CategoriesTable = &categoriesTableType{
	s: parse.StructInfo{
		Type:    "Categories",
		SQLName: "news_categories",
		Fields: []parse.FieldInfo{
			{Name: "Id", Type: "int", Column: "id"},
			{Name: "NewsId", Type: "int", Column: "news_id"},
			{Name: "CategoryId", Type: "int", Column: "category_id"},
		},
		PKFieldIndex: 0,
	},
	z: new(Categories).Values(),
}

// String returns a string representation of this struct or record.
func (s Categories) String() string {
	res := make([]string, 3)
	res[0] = "Id: " + reform.Inspect(s.Id, true)
	res[1] = "NewsId: " + reform.Inspect(s.NewsId, true)
	res[2] = "CategoryId: " + reform.Inspect(s.CategoryId, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Categories) Values() []interface{} {
	return []interface{}{
		s.Id,
		s.NewsId,
		s.CategoryId,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Categories) Pointers() []interface{} {
	return []interface{}{
		&s.Id,
		&s.NewsId,
		&s.CategoryId,
	}
}

// View returns View object for that struct.
func (s *Categories) View() reform.View {
	return CategoriesTable
}

// Table returns Table object for that record.
func (s *Categories) Table() reform.Table {
	return CategoriesTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Categories) PKValue() interface{} {
	return s.Id
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Categories) PKPointer() interface{} {
	return &s.Id
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Categories) HasPK() bool {
	return s.Id != CategoriesTable.z[CategoriesTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.Id = pk.
func (s *Categories) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = CategoriesTable
	_ reform.Struct = (*Categories)(nil)
	_ reform.Table  = CategoriesTable
	_ reform.Record = (*Categories)(nil)
	_ fmt.Stringer  = (*Categories)(nil)
)

func init() {
	parse.AssertUpToDate(&CategoriesTable.s, new(Categories))
}
